Fix severe build problems under foreign architecture and update README.md

diff --git a/bananui-base-0.1.1/debian/postinst b/bananui-base-0.1.1/debian/postinst
--- a/bananui-base-0.1.1/debian/postinst
+++ b/bananui-base-0.1.1/debian/postinst
@@ -1,3 +1,9 @@
 #!/bin/sh
-update-rc.d bananui defaults
+set -e
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/bananui" ]; then
+		update-rc.d bananui >/dev/null
+		invoke-rc.d bananui start
+	fi
+fi
 #DEBHELPER#
diff --git a/check-deps b/check-deps
--- a/check-deps
+++ b/check-deps
@@ -2,22 +2,6 @@
 	
 CROSS_COMPILE=${2:-arm*-linux-gnueabihf*}
 
-findarmgcc () {
-	for pth in `echo $PATH | sed 's/:/ /g'`; do
-		for gcc in $pth/${CROSS_COMPILE}gcc*; do
-			cat <<END > test-gcc.c
-int main() {}
-END
-			if $gcc test-gcc.c -o /dev/null > /dev/null 2>&1; then
-				echo $gcc
-				rm test-gcc.c
-				exit 0
-			fi
-			rm test-gcc.c
-		done
-	done
-	exit 1
-}
 missing () {
 	echo "Missing program $1." 1>&2
 	if [ "$2" ]; then
@@ -33,9 +17,16 @@ check () {
 	which debootstrap || missing debootstrap
 }
 checkgcc () {
-	if [ -z "$1" ]; then
-		echo "Could not find a GCC compiler for $CROSS_COMPILE."
-		exit 1
+	gcc="arm-linux-gnueabihf-gcc"
+	cat <<END > test-gcc.c
+int main() {}
+END
+	if $gcc test-gcc.c -o /dev/null > /dev/null 2>&1; then
+		rm test-gcc.c
+		exit 0
 	fi
+	rm test-gcc.c
+	echo "Could not find a GCC compiler for $CROSS_COMPILE."
+	exit 1
 }
 $@
diff --git a/device-startup-0.1.1/debian/postinst b/device-startup-0.1.1/debian/postinst
--- a/device-startup-0.1.1/debian/postinst
+++ b/device-startup-0.1.1/debian/postinst
@@ -1,4 +1,15 @@
 #!/bin/sh
-update-rc.d wifi defaults
-update-rc.d usb defaults
+set -e
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/usb" ]; then
+		update-rc.d usb defaults >/dev/null
+		invoke-rc.d usb start
+	fi
+fi
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/wifi" ]; then
+		update-rc.d wifi defaults >/dev/null
+		invoke-rc.d wifi start
+	fi
+fi
 #DEBHELPER#
