Get dependency information dynamically from the built packages, ...
 - fix build-packages problem, grep was missing an argument
 - define the syntaxerr function in copy-packages

diff --git a/scripts/copy-packages b/scripts/copy-packages
--- a/scripts/copy-packages
+++ b/scripts/copy-packages
@@ -2,7 +2,13 @@
 
 set -e
 
-echo "==>> Copying packages:"
+echo "==>> Copying packages:" 1>&2
+
+syntaxerr () {
+	echo "Syntax error: $1" 1>&2
+	exit 1
+}
+
 
 while read package; do
 	case "$package" in
