Switch to menuconfig

diff --git a/scripts/download-packages b/scripts/download-packages
--- a/scripts/download-packages
+++ b/scripts/download-packages
@@ -5,31 +5,82 @@ set -e
 branch=$(git branch --show-current)
 if [ -z "$branch" ]; then branch=stable; fi
 
-while read firstpackage packages; do
-	package_from_source=0
-	while read package_build; do
-		packagename_build=$(echo "$package_build" | cut -f 1)
-		packagesource=$(echo "$package_build" | cut -f 2)
-		packagefile_build=$(echo "$package_build" | cut -f 3)
-		if [ "$packagefile_build" = "$firstpackage" ]; then
-			package_from_source=1
-			if [ -d "$packagename_build" ]; then
-				if [ -d "$packagename_build/.git" ]; then
-					(cd "$packagename_build" && git pull)
-				fi
-			else
-				git clone "$packagesource" "$packagename_build" -b "$branch"
+syntaxerr () {
+	echo "Syntax error: $1" 1>&2
+	exit 1
+}
+
+
+while read package; do
+	case "$package" in
+		"#"*|"")
+			continue
+			;;
+	esac
+	configname=$(echo "$package" | cut -f 1)
+	packages=$(echo "$package" | cut -f 2)
+	packagename=$(echo "$packages" | sed 's/,.*$//' | cut -d : -f 1)
+	packagesource=""
+	while true; do
+		case "$packagesource" in
+			"#"*|"")
+				read packagesource || syntaxerr \
+					"Expected source URL, found EOF"
+				continue
+				;;
+			*)
+				break
+				;;
+		esac
+	done
+	package_2=""
+	while true; do
+		case "$package_2" in
+			"#"*|"")
+				read package_2 || syntaxerr \
+					"Expected arch,version,opt; found EOF"
+				continue
+				;;
+			*)
+				break
+				;;
+		esac
+	done
+	packagever=$(echo "$package_2" | cut -f 1)
+	packagepriority=$(echo "$package_2" | cut -f 2)
+	packagedeps="#"
+	read packagedeps || syntaxerr "Expected dependencies, found EOF"
+	while true; do
+		case "$packagedeps" in
+			"#"*)
+				read packagedeps || syntaxerr \
+					"Expected dependencies, found EOF"
+				continue
+				;;
+			*)
+				break
+				;;
+		esac
+	done
+	if grep -q "^${configname}_BUILD=y" .config; then
+		if [ -d "$packagename" ]; then
+			if [ -d "$packagename/.git" ]; then
+				(cd "$packagename" && git pull)
 			fi
+		else
+			git clone "$packagesource" "$packagename" -b "$branch"
 		fi
-	done < .packages-build
-	if [ "x$package_from_source" != "x1" ]; then
+	elif grep -q "^${configname}_DOWNLOAD=y" .config; then
 		if [ "x$RELEASE" != "x1" ]; then
+			echo "==>> Can't download $packages:"
 			echo "==>> ERROR: This is a development version. No pre-built packages are available." 1>&2
-			echo "===>> Please reconfigure: make config" 1>&2
+			echo "===>> Please reconfigure: make menuconfig" 1>&2
 			exit 1
 		fi
-		for package in $firstpackage $packages; do
-			wget -c "https://affenull2345.gitlab.io/bananian/packages-latest/$package"
+		for debname_arch in $(echo "$packages" | sed 's/,/ /g'); do
+			debname=$(echo "$debname_arch" | cut -d : -f 1)
+			arch=$(echo "$debname_arch" | cut -d : -f 2)
+			wget -c "https://affenull2345.gitlab.io/bananian/packages-latest/${debname}_${packagever}_${arch}.deb"
 		done
 	fi
-done < .packages
+done < packages/packages.list
